// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCodCF9qhkT8JB0jAS1mNDBfBV5EA0AVoE',
    appId: '1:500539272721:web:f6132750d7a2e2a75e4bb0',
    messagingSenderId: '500539272721',
    projectId: 'praktyk-cb1c1',
    authDomain: 'praktyk-cb1c1.firebaseapp.com',
    storageBucket: 'praktyk-cb1c1.appspot.com',
    measurementId: 'G-MY748XX7WR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFmh-Rp4DK_4GI5mNl2zKZwDslvoB1ehM',
    appId: '1:500539272721:android:2fb16e3ef3208edf5e4bb0',
    messagingSenderId: '500539272721',
    projectId: 'praktyk-cb1c1',
    storageBucket: 'praktyk-cb1c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9v6lkUPcEqP9oIYghUlYZLuZcXaCtYmo',
    appId: '1:500539272721:ios:7350c83af7aa8c745e4bb0',
    messagingSenderId: '500539272721',
    projectId: 'praktyk-cb1c1',
    storageBucket: 'praktyk-cb1c1.appspot.com',
    iosBundleId: 'com.example.eLearningApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9v6lkUPcEqP9oIYghUlYZLuZcXaCtYmo',
    appId: '1:500539272721:ios:383890707066577e5e4bb0',
    messagingSenderId: '500539272721',
    projectId: 'praktyk-cb1c1',
    storageBucket: 'praktyk-cb1c1.appspot.com',
    iosBundleId: 'com.example.eLearningAppMaster',
  );
}
